baseURL: "https://dev-helia.github.io/Tech-Blog-Website/"
title: "Helia's Tech-Blog"  # è¿™é‡Œæ›´æ–°ä¸ºæ–°åå­—
theme: "PaperMod"

pagination:
  pagerSize: 6

languageCode: "en-us"
defaultContentLanguage: "en"
enableRobotsTXT: true

params:
  env: production
  description: "A collection of curated prompts, AI thoughts, and tech experiments by Helia"
  author: Helia
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  UseHugoToc: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: false

  homeInfoParams:
    Title: "ğŸ‘‹ Welcome to Helia's Tech-Blog"  # ä¿®æ”¹æ¬¢è¿æ ‡é¢˜
    Content: |
      Hi, I'm Helia.  
      Welcome to my little corner.

  socialIcons:
    - name: github
      url: "https://github.com/dev-helia"
    - name: email
      url: "mailto:hetaoo.c@gmail.com"
    - name: rss
      url: "https://dev-helia.github.io/Tech-Blog-Website/index.xml"  # ä¿®æ”¹ rss çš„é“¾æ¥

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON
